- name: Copy db private_key
  copy:
    src: /Users/scott.krutsinger/Documents/vagrant/devstack/.vagrant/machines/pg1.techraving.com/virtualbox/private_key
    dest: /root/pg1_private_key
    mode: '0600'

- name: Copy ui1 private_key
  copy:
    src: /Users/scott.krutsinger/Documents/vagrant/devstack/.vagrant/machines/pg2.techraving.com/virtualbox/private_key
    dest: /root/pg2_private_key
    mode: '0600'

- name: Copy ui2 private_key
  copy:
    src: /Users/scott.krutsinger/Documents/vagrant/devstack/.vagrant/machines/lb-databases.techraving.com/virtualbox/private_key
    dest: /root/lb_private_key
    mode: '0600' 