---

# - name: Update packages
#   hosts: all
#   become: true

#   tasks:
#   - name: Update Kernel
#     yum:
#       name: kernel 
#       state: latest

#   - name: update packages 
#     yum:
#       name: '*'
#       state: latest

#   - name: Install Firewalld 
#     yum:
#       name: 'firewalld'
#       state: latest

#   - name: Stop firewalld
#     service:
#       name: firewalld
#       state: stopped
#       enabled: false

# - name: Install Postgresql Databases
#   hosts: database, database_replica
#   become: true

#   roles:
#     - role: "postgres_install"

- name: Replicate Postgresql Databases
  hosts: database, database_replica
  become: true

  roles:
    - role: "postgres_replication"

# - name: Replicate Postgresql HAProxy
#   hosts: lb_databases
#   become: true

#   roles:
#     - role: "postgres_haproxy"

# - name: Prepare UI Servers
#   hosts: ui
#   become: true

#   roles:
#     - role: "prepare_servers"

# - name: Install Ansible Tower
#   hosts: ui[0]
#   become: true

#   roles:
#     - role: "tower_install"

# - name: Install Load Balancer for Ansible Tower UI
#   hosts: lb_ui
#   become: true

#   roles:
#     - role: "tower_haproxy"
#       vars:
#         lb_groups_key: 'ui'

# - name: Update ui servers to point to Postgresl Load Balancer
#   hosts: ui
#   become: true

#   tasks:
#     - name: Update the postgres.py
#       lineinfile:
#         path: /etc/tower/conf.d/postgres.py
#         regexp: "'HOST': '{{ groups['database'][0] }}',"
#         line: "'HOST': '{{ groups['lb_databases'][0] }}',"
#       when: groups['lb_databases']|length > 0

#     - name: Restart tower
#       command: ansible-tower-service restart
#       when: groups['lb_databases']|length > 0